repos:
  - repo: local
    hooks:
      - id: cargo-test
        name: Run cargo tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt
        name: Run cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false
