[package]
name = "scl"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
pratt-derive = { path = "pratt-derive" }
qbe = "2.5.0"
strum = { version = "0.27.1", features = ["derive"] }
thiserror = "2.0.12"
