use std::io::printf

proc main() i32 {
    printf("9 < 10 = %d\n", 9 < 10);
    printf("10 < 10 = %d\n", 10 < 10);
    printf("11 < 10 = %d\n", 11 < 10);

    printf("9 <= 10 = %d\n", 9 <= 10);
    printf("10 <= 10 = %d\n", 10 <= 10);
    printf("11 <= 10 = %d\n", 11 <= 10);

    printf("9 > 10 = %d\n", 9 > 10);
    printf("10 > 10 = %d\n", 10 > 10);
    printf("11 > 10 = %d\n", 11 > 10);

    printf("9 >= 10 = %d\n", 9 >= 10);
    printf("10 >= 10 = %d\n", 10 >= 10);
    printf("11 >= 10 = %d\n", 11 >= 10);

    0
}
